# Use the latest 2.1 version of CircleCI pipelines.
version: 2.1

# Define reusable commands
commands:
  # Command to install dependencies
  install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt

  # Command to run Pylint
  run_pylint:
    steps:
      - run:
          name: Run Pylint
          command: |
            . venv/bin/activate
            pylint app tests

  # Command to run Pytest
  run_pytest:
    steps:
      - run:
          name: Run Pytest
          command: |
            . venv/bin/activate
            pytest tests

# Define the jobs in the pipeline
jobs:
  build-and-test-staging:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - install_dependencies
      - run_pylint
      - run_pytest

  merge-to-main:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Configure Git User
          command: |
            git config user.email "$GIT_EMAIL"
            git config user.name "$GIT_USER"
      - run:
          name: Merge staging to main
          command: |
            git checkout main
            git merge staging --no-ff -m "Automated merge from staging after successful CI"
            git remote set-url origin "https://$GITHUB_USER:$GITHUB_TOKEN@github.com/gsmafra/reverse-akinator.git"
            git push origin main
    needs:
      - build-and-test-staging

# Define the workflows in the pipeline
workflows:
  version: 2
  staging-to-main:
    jobs:
      - build-and-test-staging:
          name: Build and Test Staging
          filters:
            branches:
              only:
                - staging
      - merge-to-main:
          name: Merge to Main
          requires:
            - build-and-test-staging
          filters:
            branches:
              only:
                - staging
