CHARACTERS = [
    "Pikachu",
    "Mario",
    "Harry Potter",
    "Wonder Woman",
    "Spider-Man",
    "Mickey Mouse",
    "Luke Skywalker",
    "Hermione Granger",
    "Batman",
    "SpongeBob SquarePants",
    "Naruto Uzumaki",
    "Goku",
    "Darth Vader",
    "The Joker",
    "Jesus Christ",
    "Adolf Hitler",
    "Elvis Presley",
    "Arnold Schwarzenegger",
    "Madonna",
    "Barack Obama",
    "Donald Trump",
    "Beyonce",
    "Eminem",
    "50 Cent",
    "Rihanna",
    "Justin Bieber",
    "Tayler Swift",
    "Pelé",
    "Cristiano Ronaldo",
    "Lionel Messi",
    "Neymar",
    "Ronaldinho",
    "Angelina Jolie",
    "Brad Pitt",
    "Tom Cruise",
    "Vegeta",
    "Queen Elizabeth II",
    "Napoleon Bonaparte",
    "Abraham Lincoln",
    "Joseph Stalin",
    "Mao Zedong",
    "Prophet Muhammad",
    "Julius Caesar",
    "Augustus",
    "Alexander the Great",
    "Albert Einstein",
    "Isaac Newton",
    "Michael Corleone",
    "Woody",
    "Buzz Lightyear",
]
